### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by IbrahimFangary** [GYQ-form/RGAST#1]
i use Colab and can't download or clone the repository, I always get 

> Collecting RGAST
>   Using cached RGAST-0.0.1-py3-none-any.whl.metadata (2.0 kB)
> Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from RGAST) (2.4.0)
> Requirement already satisfied: scanpy in /usr/local/lib/python3.10/dist-packages (from RGAST) (1.10.2)
> Collecting sklearn (from RGAST)
>   Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> See above for output.
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   Preparing metadata (setup.py) ... error
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

even when I clone the repo it says the same issue with sklearn-0.0.post12.tar.gz

**Comment by GYQ-form** [comment]
Thank you for reporting this issue!

In the process of further development, we have noticed this issue and fixed it in `dev` branch. However we forgot to fix it in the `main` branch. Now we have solved this problem and you should find it work out well! Feel free to contact me if you have any other problems.

Best regards,
Yuqiao Gong
